name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: "CI"
    runs-on: "ubunt--latest"
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: test
      run: dotnet test --configuration Release

    - name: Build Application
      run: dotnet publish DemoApi/DemoApi.csproj -c Release -o artifacts

    - uses: actions/upload-artifact@v4
      with:
        name: "upload artifacts"
        path: artifacts/

