name: CI

env:
  IMAGE_NAME: 'hanzalah/demoapi'
  WORKING_DIRECTORY: './DemoApi'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "sample ci pipeline"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: restore
        working-directory: ./DemoApi
        run: dotnet restore

      - name: build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet build --configuration Release

      - name: Build Application
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: dotnet publish -c Release -o out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t $IMAGE_NAME:latest -f ./Dockerfile .
          docker push $IMAGE_NAME:latest

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
