name: Demo secrets

on:
  pull_request: 
    branches: [ "main" ]
  workflow_dispatch:

env:
  TOPLEVEL_ENV_VAR: 'Hanz'

jobs:
  job1:
    name: demmo
    runs-on: ubuntu-latest
    env:
      JOBLEVEL_ENV_VAR: 'JOB1'
    steps:
      - name: demoe env and secrets
        run: |
          echo "job1: top level env $TOPLEVEL_ENV_VAR"
          echo "job1: job level env $JOBLEVEL_ENV_VAR"

  job2:
    name: demmo
    runs-on: ubuntu-latest
    env:
      JOBLEVEL_ENV_VAR: 'JOB2'
    steps:
      - name: demoe env and secrets
        run: |
          echo "job2: top level env $TOPLEVEL_ENV_VAR"
          echo "job2: job level env $JOBLEVEL_ENV_VAR"